### ISSUE TITLE
MultiQC v2.0 tracker

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#1784]
Change is on the breeze. This issue is a tracking issue for things that I want to put into a v2.0 release with major refactoring.

## Organisational

- [ ] Move to the MultiQC GitHub organisation
- [ ] Set up a MultiQC Slack
- [ ] Set up a maintainers team
- [ ] https://github.com/ewels/MultiQC_website/issues/15
- [ ] Split modules out into separate Python packages

## Practical

- [ ] Replace plotting library
- [ ] https://github.com/ewels/MultiQC/issues/1698
- [ ] Refactor core code to use Pydantic objects
- [ ] Lint for variable typing with mypy
- [ ] https://github.com/ewels/MultiQC/issues/1256
- [ ] https://github.com/ewels/MultiQC/issues/1051
