### ISSUE TITLE
Create child templates

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#63]
At the moment, every template is stand alone. This means that if you just want to change the logo, or a bit of text in the report, then you have to copy everything from `general` and then make your change. Inevitably, this leads to drift away from the core package and theme.

Instead, allow templates to behave as 'child' themes. Could set a variable `parent` in the theme `__init__.py` with the name of another template and build off that. Then the parent template would be used, with any files in the child copied over the top of this. This could happen at run time, also allowing plugin packages to keep their code base clean.

To make this work, I need to split up the template into many more files instead of a single massive file. This is thankfully very easy with Jinja2 - see the [docs](http://jinja.pocoo.org/docs/dev/templates/#child-template).

Also, whilst the new stand-alone reports are very nice, we probably need to allow themes to create non stand-alone reports if they want to. Again, an option in the report's `__init__.py` file here I think.

**Task list:**
- [x] Split `general` Jinja template into multiple files, centred on a [`base.html`](http://jinja.pocoo.org/docs/dev/templates/#base-template) with `blocks`
- [x] New optional variable in template `__init__.py` to specify parent theme
- [x] New method of report generation, involving copying template files to a temporary location
  - See [`tempfile.mkdtemp()`](https://docs.python.org/2/library/tempfile.html#tempfile.mkdtemp)
- [x] New template `__init__.py` config option to prepend a directory name to generated report
- [x] New template `__init__.py` ability to copy files along with report generation.
